name: Check Release
on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: check-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check_release:
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
